### ISSUE TITLE
[UI]Landing Page

### ISSUE THREAD

**Issue by varisha-025** [varisha-025/BizRank#13]
The design of the landing page has been attatched.
Use of Material Ui will be preferred

![Image](https://user-images.githubusercontent.com/81171573/194769353-ac51606e-5f54-475a-810e-092964050146.jpeg)
![Image](https://user-images.githubusercontent.com/81171573/194769358-7a85bee1-a0e0-4b97-9b9f-85d355f77be9.jpeg)
![Image](https://user-images.githubusercontent.com/81171573/194769364-3ffddaef-214d-4fbe-941e-7f7c77e4c439.jpeg)
![Image](https://user-images.githubusercontent.com/81171573/194769365-01f0f489-5c87-4b4c-a267-9df1e6fbf6d3.jpeg)
![Image](https://user-images.githubusercontent.com/81171573/194769367-0d61641a-77a2-404a-b05e-ebabfb2824fa.jpeg)
![Image](https://user-images.githubusercontent.com/81171573/194769366-f91e29eb-8188-460a-9d1f-7b1195b3cd3c.jpeg)

The link of the figma file has also been mentioned.

https://www.figma.com/file/4pAZAKMFpPMDlu7iR8DYjC/Small-Business-Rating-System?node-id=48%3A420

**Comment by mohithgupta** [comment]
Please verify the link - It says, either not found or not permitted
Also to be called a "good first issue" this is too much work ;)

**Comment by Im-Kunal-13** [comment]
@varisha-025 I would like to work on this. Can you assign this to me?

**Comment by ASANIYAN** [comment]
Hello, the figma file link is still saying "file not found"

**Comment by varisha-025** [comment]
Please check now if the file is opening @ASANIYAN
