### ISSUE TITLE
[DESIGN]Design a logo for the website

### ISSUE THREAD

**Issue by varisha-025** [varisha-025/BizRank#17]

**Comment by trybick** [comment]
Hi I can design this

**Comment by trybick** [comment]
@varisha-025 Do you like either of these?

![logo](https://user-images.githubusercontent.com/39889198/194772182-9df78947-b9f9-44bf-b7ea-ff235cd6c72d.png)

![logo](https://user-images.githubusercontent.com/39889198/194772207-06f28b52-9adc-4672-8daa-9a7c512da77e.png)

**Comment by varisha-025** [comment]
@trybick I have assigned you the issue. I want the logo to be decent and either related to the purpose of the website or based on the name 'BizRank'

**Comment by varisha-025** [comment]
As I mentioned, I want either a logo based on name which has no other elements.

**Comment by trybick** [comment]
Do you like either of these? If so, where do you want them located in the repo?

![logo](https://user-images.githubusercontent.com/39889198/194772630-170876e8-1418-487a-93c6-daf1d425afc3.png)

![logo](https://user-images.githubusercontent.com/39889198/194772651-20431023-1009-47af-abf8-82152618c826.png)

**Comment by varisha-025** [comment]
@trybick , I would prefer if the logo has a star because this is a rating website.

**Comment by trybick** [comment]
I wasn't able to find a star, but does this work? Note: I can make one more maximum after this. 
![logo](https://user-images.githubusercontent.com/39889198/194849706-d15ce258-05dd-42d2-a445-afe57e63d757.png)

**Comment by varisha-025** [comment]
@trybick I like this one

**Comment by trybick** [comment]
Would you like me to open a PR to add it?

**Comment by varisha-025** [comment]
Sure @trybick . Go ahead and add it to the navbar of the website for now.

**Comment by trybick** [comment]
Opened PR to add to navbar #19
