### ISSUE TITLE
[UI] Footer

### ISSUE THREAD

**Issue by varisha-025** [varisha-025/BizRank#27]
![Image](https://user-images.githubusercontent.com/81171573/197129711-35aae295-f175-4586-97a2-412be2326305.jpeg)

Ignore the `LOGO` part as of now, include 3 social media icons with some nice hover effects:

- Instagram
- Facebook
- Gmail

A component named `Footer` is already present in the `Layout` folder, just change the exisitng code.

**Comment by jeroenekkelkamp** [comment]
Can i work on this one?

**Comment by varisha-025** [comment]
@jeroenekkelkamp why did you close the pull request everything was correct you just had to squash the commits
