### ISSUE TITLE
[UI] Body of Landing Page (2nd)

### ISSUE THREAD

**Issue by varisha-025** [varisha-025/BizRank#29]
![Image](https://user-images.githubusercontent.com/81171573/197132611-d34cc7ad-45cc-4535-a2cf-867310c66862.jpeg)

A new component should be created in the `Layout` folder and then included in the `Home` page after the `Header` component.

**Comment by shrutilenka** [comment]
Hey @varisha-025 I am interested to work on this issue.Could you please assign this to me?

**Comment by varisha-025** [comment]
@shrutilenka i have assigned you the issue

**Comment by shrutilenka** [comment]
@varisha-025 can I change the whole UI which is done previously?
apart from the header and the body what else is needed for your website? can you pls jot it down here

**Comment by varisha-025** [comment]
@shrutilenka Please don't make any other changes right now. I will be making more issues today, you can comment there if you want it. The design of the landing page has already been finalized.

**Comment by varisha-025** [comment]
@Athi223 Do you want to work on this issue?

**Comment by Athi223** [comment]
@varisha-025 Sure I'd like to give it a try

**Comment by varisha-025** [comment]
Okay. You have 1 day for this. use tailwind css for this.

**Comment by Athi223** [comment]
@varisha-025 Hey actually I haven't really worked worked with _tailwind_ before, so you could assign someone else. Sorry for that. Thanks for the opportunity though!
