### ISSUE TITLE
[UI] Body of landing page (1st)

### ISSUE THREAD

**Issue by varisha-025** [varisha-025/BizRank#38]
![Image](https://user-images.githubusercontent.com/81171573/197378334-4f450408-3ca7-401b-b855-c156b4109f21.jpeg)

A body component should be created in the `Layout` folder and then included in the `Home` page after the `Header` component.

**Comment by varisha-025** [comment]
@shrutilenka Do you want to work on this issue too?

**Comment by shrutilenka** [comment]
@varisha-025 sure.let me first solve this issue then I will move to the 2nd an d3rd part of it.

**Comment by shrutilenka** [comment]
Should I unassign myself from the 2nd one? @varisha-025

**Comment by varisha-025** [comment]
@shrutilenka No No, first make PR for this one or you can combine all three of them into one `Body` component, that will be the best solution. Don't unassign yourself as you only have to solve all the three parts.

**Comment by shrutilenka** [comment]
@varisha-025 can you share the illustrations SVGs? or shall I put some dummy illustraions?

**Comment by varisha-025** [comment]
Use dummy illusttations @shrutilenka
