### ISSUE TITLE
[UI] Body of landing page (3rd)

### ISSUE THREAD

**Issue by varisha-025** [varisha-025/BizRank#41]
![Image](https://user-images.githubusercontent.com/81171573/197378620-3938e9a3-5bb4-4e0c-9a22-5f149596938d.jpeg)

**Comment by varisha-025** [comment]
@shrutilenka

**Comment by KrunalGupta02** [comment]
Can i work on it

**Comment by varisha-025** [comment]
@KrunalGupta02 #15 issue is open currently. If you want this issue then let me know.

**Comment by KrunalGupta02** [comment]
> @KrunalGupta02 #15 issue is open currently. If you want this issue then let me know. 

Yeah i want to work on it plz !assign me

**Comment by varisha-025** [comment]
@KrunalGupta02 please comment on that issue

**Comment by KrunalGupta02** [comment]
> @KrunalGupta02 please comment on that issue

Where

**Comment by KrunalGupta02** [comment]
> Issue #15 so that i can assign you

Done 👍🏻

**Comment by varisha-025** [comment]
@KrunalGupta02 I have assigned this issue to you
